### ISSUE TITLE
Can't use the docker version on Mac OS Big Sur (11.2.3)

### ISSUE THREAD

**Issue by gorinje** [etalab/piaf#34]
The _docker-compose pull_  command provides the following error :
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[11847] Failed to execute script docker-compose

**Comment by guillim** [comment]
Does docker engine work on your machine ? Like for instance can you run `docker run -d -p 80:80 docker/getting-started
` ? I am asking to know if it is related only to docker-compose

**Comment by gorinje** [comment]
OOoops, right :)
